import { createPublicClient, createWalletClient, custom, http, parseUnits } from "viem"
import { sepolia } from "viem/chains"

export const escrowAddress = import.meta.env.VITE_ESCROW_CONTRACT_ADDRESS as `0x${string}` | undefined
export const disputeAddress = import.meta.env.VITE_DISPUTE_CONTRACT_ADDRESS as `0x${string}` | undefined
export const usdcAddress = import.meta.env.VITE_USDC_ADDRESS as `0x${string}` | undefined
export const publicClient = import.meta.env.VITE_SEPOLIA_RPC_URL ? createPublicClient({ chain: sepolia, transport: http(import.meta.env.VITE_SEPOLIA_RPC_URL) }) : undefined
export const ERC20_ABI = [{ type:"function",name:"decimals",stateMutability:"view",inputs:[],outputs:[{type:"uint8"}] },{ type:"function",name:"balanceOf",stateMutability:"view",inputs:[{type:"address",name:"owner"}],outputs:[{type:"uint256"}] },{ type:"function",name:"allowance",stateMutability:"view",inputs:[{type:"address",name:"owner"},{type:"address",name:"spender"}],outputs:[{type:"uint256"}] },{ type:"function",name:"approve",stateMutability:"nonpayable",inputs:[{type:"address",name:"spender"},{type:"uint256",name:"amount"}],outputs:[{type:"bool"}] }] as const
export const ESCROW_ABI = [{type:"function",name:"createEscrow",stateMutability:"nonpayable",inputs:[{type:"string",name:"projectId"},{type:"address",name:"freelancer"},{type:"address",name:"token"},{type:"uint256[]",name:"milestoneAmounts"}],outputs:[]},{type:"function",name:"fund",stateMutability:"nonpayable",inputs:[{type:"string",name:"projectId"}],outputs:[]},{type:"function",name:"releaseMilestone",stateMutability:"nonpayable",inputs:[{type:"string",name:"projectId"},{type:"uint256",name:"index"}],outputs:[]},{type:"function",name:"getEscrowParties",stateMutability:"view",inputs:[{type:"string",name:"projectId"}],outputs:[{type:"address",name:"client"},{type:"address",name:"freelancer"},{type:"bool",name:"isFunded"},{type:"bool",name:"isDisputed"},{type:"bool",name:"isCompleted"}]}] as const
export const DISPUTE_ABI = [{type:"function",name:"raiseDispute",stateMutability:"nonpayable",inputs:[{type:"string",name:"projectId"},{type:"string",name:"reason"}],outputs:[]}] as const
export async function connectWallet() { if (!window.ethereum) throw new Error("No browser wallet was found."); const wallet = createWalletClient({ chain: sepolia, transport: custom(window.ethereum) }); const [account] = await wallet.requestAddresses(); if (await wallet.getChainId() !== sepolia.id) await wallet.switchChain({ id: sepolia.id }); return { wallet, account }; }
function configured() { if (!publicClient || !escrowAddress || !disputeAddress || !usdcAddress) throw new Error("Blockchain configuration is incomplete."); return { publicClient, escrowAddress, disputeAddress, usdcAddress }; }
async function units(token: `0x${string}`, amount: string) { const c = configured(); const decimals = await c.publicClient.readContract({ address: token, abi: ERC20_ABI, functionName:"decimals" }); return parseUnits(amount, decimals); }
async function confirm(hash: `0x${string}`) { const receipt = await configured().publicClient.waitForTransactionReceipt({ hash }); if (receipt.status !== "success") throw new Error("Transaction reverted."); }
function requireVerifiedAccount(account: `0x${string}`, verifiedWallet: string) { if (!verifiedWallet || account.toLowerCase() !== verifiedWallet.toLowerCase()) throw new Error("Connect the wallet verified for this FairWork account."); }
export async function fundEscrow(projectId:string, freelancer:`0x${string}`, amountsText:string[], verifiedWallet:string, onStage:(value:string)=>void) { const c=configured(); const {wallet,account}=await connectWallet(); requireVerifiedAccount(account, verifiedWallet); const amounts=await Promise.all(amountsText.map((a)=>units(c.usdcAddress,a))); const total=amounts.reduce((a,b)=>a+b,0n); if(await c.publicClient.readContract({address:c.usdcAddress,abi:ERC20_ABI,functionName:"balanceOf",args:[account]})<total) throw new Error("Insufficient token balance."); const escrow=await c.publicClient.readContract({address:c.escrowAddress,abi:ESCROW_ABI,functionName:"getEscrowParties",args:[projectId]}); if(escrow[0]==="0x0000000000000000000000000000000000000000"){onStage("Creating escrow");await confirm(await wallet.writeContract({account,address:c.escrowAddress,abi:ESCROW_ABI,functionName:"createEscrow",args:[projectId,freelancer,c.usdcAddress,amounts]}));}else if(escrow[0].toLowerCase()!==account.toLowerCase())throw new Error("Connected wallet is not this escrow's client."); if(await c.publicClient.readContract({address:c.usdcAddress,abi:ERC20_ABI,functionName:"allowance",args:[account,c.escrowAddress]})<total){onStage("Approving token allowance");await confirm(await wallet.writeContract({account,address:c.usdcAddress,abi:ERC20_ABI,functionName:"approve",args:[c.escrowAddress,total]}));}onStage("Funding escrow");await confirm(await wallet.writeContract({account,address:c.escrowAddress,abi:ESCROW_ABI,functionName:"fund",args:[projectId]})); }
export async function releaseEscrowMilestone(projectId:string,index:number,verifiedWallet:string){const c=configured();const {wallet,account}=await connectWallet();requireVerifiedAccount(account,verifiedWallet);await confirm(await wallet.writeContract({account,address:c.escrowAddress,abi:ESCROW_ABI,functionName:"releaseMilestone",args:[projectId,BigInt(index)]}));}
export async function raiseEscrowDispute(projectId:string,reason:string,verifiedWallet:string){const c=configured();const {wallet,account}=await connectWallet();requireVerifiedAccount(account,verifiedWallet);await confirm(await wallet.writeContract({account,address:c.disputeAddress,abi:DISPUTE_ABI,functionName:"raiseDispute",args:[projectId,reason]}));}
